/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "interface.h"
#include "support.h"
#include "callbacks.h"
#include "trainers.h"

/* Global trainer list */
TrainerList *trainer_list = NULL;

int main(int argc, char *argv[])
{
  GtkWidget *espace_administratif;
  
#ifdef ENABLE_NLS
  bindtextdomain(GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset(GETTEXT_PACKAGE, "UTF-8");
  textdomain(GETTEXT_PACKAGE);
#endif

  gtk_set_locale();
  gtk_init(&argc, &argv);



  /* Initialize trainer data */
  trainer_list = create_trainer_list();
  if (trainer_list == NULL) {
    fprintf(stderr, "Error: Could not create trainer list\n");
    return 1;
  }

  /* Load trainers from file */
  if (load_trainers_from_file(trainer_list, "trainers.txt") != 0) {
    fprintf(stderr, "Note: Could not load trainers from file (might be first run)\n");
  } else {
    fprintf(stderr, "Successfully loaded trainers from file\n");
  }

  /* Show espace_administratif window directly */
  espace_administratif = create_espace_administratif();
  gtk_widget_show(espace_administratif);

  /* Initialize dashboard */
  GtkWidget *treeview = lookup_widget(espace_administratif, "ft_gestion_entraineur_dashboard_treeview");
  if (treeview) {
    initialize_dashboard(treeview);
    refresh_dashboard(treeview);
  }

  /* Load specialties for combo boxes */
  GtkWidget *combo_add = lookup_widget(espace_administratif, "ft_gestion_entraineur_ajouter_specialite_comboboxentry");
  GtkWidget *combo_modify = lookup_widget(espace_administratif, "ft_gestion_entraineur_modifier_specialite_comboboxentry");
  
  if (combo_add) load_specialties_to_combobox(GTK_COMBO_BOX(combo_add));
  if (combo_modify) load_specialties_to_combobox(GTK_COMBO_BOX(combo_modify));

  /* Generate initial ID */
 // generate_next_id(espace_administratif);

  gtk_main();

  /* Cleanup */
  save_trainers_to_file(trainer_list, "trainers.txt");
  free_trainer_list(trainer_list);

  return 0;
}


