/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_administratif (void);
GtkWidget* create_espace_membre (void);
GtkWidget* create_espace_entraineur (void);
GtkWidget* create_login (void);
GtkWidget* create_dialog1 (void);
