/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *espace_administratif;
  GtkWidget *espace_membre;
  GtkWidget *espace_entraineur;
  GtkWidget *login;
  GtkWidget *dialog1;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  espace_administratif = create_espace_administratif ();
  gtk_widget_show (espace_administratif);
  /*espace_membre = create_espace_membre ();
  gtk_widget_show (espace_membre);
  espace_entraineur = create_espace_entraineur ();
  gtk_widget_show (espace_entraineur);
  login = create_login ();
  gtk_widget_show (login);
  dialog1 = create_dialog1 ();
  gtk_widget_show (dialog1);*/

  gtk_main ();
  return 0;
}

